[theme]
base="dark"
primaryColor="#5e4ae3"
backgroundColor="#3b1d68"
secondaryBackgroundColor="#5e4ae3"
font = "Georgia"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true

[server]
headless = true
enableCORS = false
port = 8501


